# Default values for auth-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
minAvailable: 1

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  pullPolicy: IfNotPresent
  # tag: <Use to override default from Chart.yaml>

oauth:
  config:
    ## These values get pulled into oauth2_proxy.cfg template
    # clientID: abc # add Azure client-id here from the command line
    # clientSecret: def # add Azure client-secret here from the command line
    # cookieSecret: def # add random secret: python -c 'import os,base64; print base64.b64encode(os.urandom(16))'
    # cookieDomains: .domain.com
    # whitelistDomains: .domain.com
    # azureTenantID: # This is not a secret but doesn't need to be in the chart
    # cookieExpire # go duration string, defaults (absurdly) to "168h" (oauth2-proxy default)
    # cookieRefresh # go duration string, defaults to "0" (disabled)
  args:
    - --config=/etc/oauth2_proxy/oauth2_proxy.cfg

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4180

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: {}

resources:
  limits:
    memory: 20Mi
  requests:
    cpu: 200m
    memory: 15Mi

nodeSelector: {}

tolerations: []

affinity: {}
