{{- $fullName := include "auth-proxy.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "auth-proxy.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ tpl (.Files.Get "config/oauth2_proxy.cfg") . | sha256sum | substr 0 63 }}
type: Opaque
data:
  oauth2_proxy.cfg: {{ tpl (.Files.Get "config/oauth2_proxy.cfg") . | b64enc }}
